// ORDERS
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR'

export const FETCH_ORDER_START = 'FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_ERROR = 'FETCH_ORDER_ERROR'

export const CREATE_ORDER_START = 'CREATE_ORDER_START'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'

export const FETCH_ITEMS_BY_VENDOR_START = 'FETCH_ITEMS_BY_VENDOR_START'
export const FETCH_ITEMS_BY_VENDOR_SUCCESS = 'FETCH_ITEMS_BY_VENDOR_SUCCESS'
export const FETCH_ITEMS_BY_VENDOR_ERROR = 'FETCH_ITEMS_BY_VENDOR_ERROR'

export const CHANGE_ORDER_STATUS_START = 'CHANGE_ORDER_STATUS_START'
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS'
export const CHANGE_ORDER_STATUS_ERROR = 'CHANGE_ORDER_STATUS_ERROR'

export const FETCH_ORDER_PRODUCTS = 'FETCH_ORDER_PRODUCTS'

export const DELETE_ORDER_BY_ID = 'DELETE_ORDER_BY_ID'

export const FETCH_ORDER_INVOICE_START = 'FETCH_ORDER_INVOICE_START'
export const FETCH_ORDER_INVOICE_SUCCESS = 'FETCH_ORDER_INVOICE_SUCCESS'
export const FETCH_ORDER_INVOICE_ERROR = 'FETCH_ORDER_INVOICE_ERROR'

export const REMOVE_INPUT_FROM_INVOICE = 'REMOVE_INPUT_FROM_INVOICE'

// IMPORTERS
export const FETCH_IMPORTERS_START = 'FETCH_IMPORTERS_START'
export const FETCH_IMPORTERS_SUCCESS = 'FETCH_IMPORTERS_SUCCESS'
export const FETCH_IMPORTERS_ERROR = 'FETCH_IMPORTERS_ERROR'

export const FETCH_IMPORTER_START = 'FETCH_IMPORTER_START'
export const FETCH_IMPORTER_SUCCESS = 'FETCH_IMPORTER_SUCCESS'
export const FETCH_IMPORTER_ERROR = 'FETCH_IMPORTER_ERROR'

export const CREATE_IMPORTER_START = 'CREATE_IMPORTER_START'
export const CREATE_IMPORTER_SUCCESS = 'CREATE_IMPORTER_SUCCESS'
export const CREATE_IMPORTER_ERROR = 'CREATE_IMPORTER_ERROR'

export const UPDATE_IMPORTER_START = 'UPDATE_IMPORTER_START'
export const UPDATE_IMPORTER_SUCCESS = 'UPDATE_IMPORTER_SUCCESS'
export const UPDATE_IMPORTER_ERROR = 'UPDATE_IMPORTER_ERROR'

// PRODUCTS
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'

export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const FETCH_COMPARE_PRODUCTS_START = 'FETCH_COMPARE_PRODUCTS_START'
export const FETCH_COMPARE_PRODUCTS_SUCCESS = 'FETCH_COMPARE_PRODUCTS_SUCCESS'
export const FETCH_COMPARE_PRODUCTS_ERROR = 'FETCH_COMPARE_PRODUCTS_ERROR'

export const UPDATE_PRODUCT_START = 'CREATE_PRODUCT_START'
export const UPDATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const FETCH_BY_VENDOR_START = 'FETCH_BY_VENDOR_START'
export const FETCH_BY_VENDOR_SUCCESS = 'FETCH_BY_VENDOR_SUCCESS'
export const FETCH_BY_VENDOR_ERROR = 'FETCH_BY_VENDOR_ERROR'

export const FETCH_PRODUCT_PRICE = 'FETCH_PRODUCT_PRICE'

export const DELETE_PRODUCT_BY_ID = 'DELETE_PRODUCT_BY_ID'

export const UPDATE_PRODUCT_IMAGE = 'UPDATE_PRODUCT_IMAGE'

// PROVIDERS
export const FETCH_PROVIDERS_START = 'FETCH_PROVIDERS_START'
export const FETCH_PROVIDERS_SUCCESS = 'FETCH_PROVIDERS_SUCCESS'
export const FETCH_PROVIDERS_ERROR = 'FETCH_PROVIDERS_ERROR'

export const FETCH_PROVIDER_START = 'FETCH_PROVIDER_START'
export const FETCH_PROVIDER_SUCCESS = 'FETCH_PROVIDER_SUCCESS'
export const FETCH_PROVIDER_ERROR = 'FETCH_PROVIDER_ERROR'

export const CREATE_PROVIDER_START = 'CREATE_PROVIDER_START'
export const CREATE_PROVIDER_SUCCESS = 'CREATE_PROVIDER_SUCCESS'
export const CREATE_PROVIDER_ERROR = 'CREATE_PROVIDER_ERROR'

export const UPDATE_PROVIDER_START = 'UPDATE_PROVIDER_START'
export const UPDATE_PROVIDER_SUCCESS = 'UPDATE_PROVIDER_SUCCESS'
export const UPDATE_PROVIDER_ERROR = 'UPDATE_PROVIDER_ERROR'

export const DELETE_PROVIDER_BY_ID = 'DELETE_PROVIDER_BY_ID'

export const SET_BLACK_LABEL = 'SET_BLACK_LABEL'

// CONTAINERS
export const FETCH_CONTAINERS_START = 'FETCH_CONTAINERS_START'
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS'
export const FETCH_CONTAINERS_ERROR = 'FETCH_CONTAINERS_ERROR'

export const FETCH_CONTAINER_START = 'FETCH_CONTAINER_START'
export const FETCH_CONTAINER_SUCCESS = 'FETCH_CONTAINER_SUCCESS'
export const FETCH_CONTAINER_ERROR = 'FETCH_CONTAINER_ERROR'

export const CREATE_CONTAINER_START = 'CREATE_CONTAINER_START'
export const CREATE_CONTAINER_SUCCESS = 'CREATE_CONTAINER_SUCCESS'
export const CREATE_CONTAINER_ERROR = 'CREATE_CONTAINER_ERROR'

export const CHANGE_CONTAINER_STATUS_START = 'CHANGE_CONTAINER_STATUS_START'
export const CHANGE_CONTAINER_STATUS_SUCCESS = 'CHANGE_CONTAINER_STATUS_SUCCESS'
export const CHANGE_CONTAINER_STATUS_ERROR = 'CHANGE_CONTAINER_STATUS_ERROR'

export const DELETE_CONTAINER_BY_ID = 'DELETE_CONTAINER_BY_ID'

export const FETCH_UNAPPLIED_ORDERS_START = 'FETCH_UNAPPLIED_ORDERS_START'
export const FETCH_UNAPPLIED_ORDERS_SUCCESS = 'FETCH_UNAPPLIED_ORDERS_SUCCESS'
export const FETCH_UNAPPLIED_ORDERS_ERROR = 'FETCH_UNAPPLIED_ORDERS_ERROR'

// CATALOGS
export const FETCH_CATALOGS_START = 'FETCH_CATALOGS_START'
export const FETCH_CATALOGS_SUCCESS = 'FETCH_CATALOGS_SUCCESS'
export const FETCH_CATALOGS_ERROR = 'FETCH_CATALOGS_ERROR'

export const FETCH_CATALOG_START = 'FETCH_CATALOG_START'
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS'
export const FETCH_CATALOG_ERROR = 'FETCH_CATALOG_ERROR'

export const CREATE_CATALOG_START = 'CREATE_CATALOG_START'
export const CREATE_CATALOG_SUCCESS = 'CREATE_CATALOG_SUCCESS'
export const CREATE_CATALOG_ERROR = 'CREATE_CATALOG_ERROR'

// COUNTRIES
export const FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START'
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR'

export const FETCH_COUNTRY_START = 'FETCH_COUNTRY_START'
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS'
export const FETCH_COUNTRY_ERROR = 'FETCH_COUNTRY_ERROR'

export const CREATE_COUNTRY_START = 'CREATE_COUNTRY_START'
export const CREATE_COUNTRY_SUCCESS = 'CREATE_COUNTRY_SUCCESS'
export const CREATE_COUNTRY_ERROR = 'CREATE_COUNTRY_ERROR'

export const DELETE_COUNTRY_START = 'DELETE_COUNTRY_START'
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS'
export const DELETE_COUNTRY_ERROR = 'DELETE_COUNTRY_ERROR'

// TAGS
export const FETCH_TAGS_START = 'FETCH_TAGS_START'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_ERROR = 'FETCH_TAGS_ERROR'

// CITIES
export const FETCH_CITIES_START = 'FETCH_CITIES_START'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR'

// LOG
export const FETCH_LOGS_START = 'FETCH_LOGS_START'
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS'
export const FETCH_LOGS_ERROR = 'FETCH_LOGS_ERROR'

// ROLES
export const FETCH_ROLES_START = 'FETCH_ROLES_START'
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS'
export const FETCH_ROLES_ERROR = 'FETCH_ROLES_ERROR'

export const CREATE_ROLE_START = 'CREATE_ROLE_START'
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS'
export const CREATE_ROLE_ERROR = 'CREATE_ROLE_ERROR'

export const FETCH_ROLE_BY_ID_START = 'FETCH_ROLE_BY_ID_START'
export const FETCH_ROLE_BY_ID_SUCCESS = 'FETCH_ROLE_BY_ID_SUCCESS'
export const FETCH_ROLE_BY_ID_ERROR = 'FETCH_ROLE_BY_ID_ERROR'

export const UPDATE_ROLE_START = 'UPDATE_ROLE_START'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_ERROR = 'UPDATE_ROLE_ERROR'

// USERS
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

export const CREATE_USER_START = 'CREATE_USER_START'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'

export const UPDATE_USER_START = 'UPDATE_USER_START'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const FETCH_USER_BY_ID_START = 'FETCH_USER_BY_ID_START'
export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS'
export const FETCH_USER_BY_ID_ERROR = 'FETCH_USER_BY_ID_ERROR'

// EMAIL SETTINGS
export const FETCH_EMAIL_SETTINGS_START = 'FETCH_EMAIL_SETTINGS_START'
export const FETCH_EMAIL_SETTINGS_SUCCESS = 'FETCH_EMAIL_SETTINGS_SUCCESS'
export const FETCH_EMAIL_SETTINGS_ERROR = 'FETCH_EMAIL_SETTINGS_ERROR'

export const UPDATE_EMAIL_SETTINGS_START = 'UPDATE_EMAIL_SETTINGS_START'
export const UPDATE_EMAIL_SETTINGS_SUCCESS = 'UPDATE_EMAIL_SETTINGS_SUCCESS'
export const UPDATE_EMAIL_SETTINGS_ERROR = 'UPDATE_EMAIL_SETTINGS_ERROR'

export const DELETE_EMAIL_SETTINGS_START = 'DELETE_EMAIL_SETTINGS_START'
export const DELETE_EMAIL_SETTINGS_SUCCESS = 'DELETE_EMAIL_SETTINGS_SUCCESS'
export const DELETE_EMAIL_SETTINGS_ERROR = 'DELETE_EMAIL_SETTINGS_ERROR'
